export function getAircraftModel(modelName) {
    const models = {
        cessna: {
            modelPath: 'model/model.glb',
            scale: [0.01, 0.01, 0.01],
            rotation: [Math.PI / 2, Math.PI, Math.PI / 2 + Math.PI],
            position: [0, -1.675, 0],
            propellorName: 'Mesh_1',
            followCameraOffset: [0, 5, -15],
            followSmoothCameraOffset: [10, 5, -10],
            cockpitCameraOffset: [0, 0.05, 0.5],
            constants: {
                GRAVITY: 20.0,
                THRUST_FORCE: 50.0,
                MAX_THRUST: 300.0,
                REVERSE_THRUST_FORCE: 10.0,
                DRAG_COEFFICIENT: 0.1,
                LIFT_COEFFICIENT: 0.01,
                PITCH_SPEED: 0.2,
                ROLL_SPEED: 0.3,
                MAX_SPEED_LANDING: 25.0,
                MAX_SINK_RATE_LANDING: 4,
                TAKEOFF_SPEED: 25.0,
                AIRBORNE_CONFIRMATION_TIME: 5.0,
                GROUND_LEVEL: 0.5,
                RUNWAY_WIDTH: 40,
                RUNWAY_LENGTH: 700,
                SINK_RATE_THRESHOLD: 5,
            }
        },
        jet: {
            modelPath: 'model/G3_LARC_GND_0824.glb',
            airModelPath: 'model/G3_LARC_AIR_0824.glb',
            canRetractGear: true,
            // scale: [0.017, 0.017, 0.017],
            // rotation: [Math.PI / 2, Math.PI, 0],
            // position: [0, -2.675, 0],
            scale: [150, 150, 150],
            rotation: [0, 0, 0],
            position: [0, -3.33, 0],
            propellorName: 'Mesh_1',
            followCameraOffset: [0, 10, -50],
            followSmoothCameraOffset: [30, 10, -30],
            cameraDistance: 35,
            cockpitCameraOffset: [0, -1, 13],
            hitBoxScaleX: 0.8,
            hitBoxScaleY: 0.5,
            hitBoxScaleZ: 0.8,
            constants: {
                GRAVITY: 20.0,
                THRUST_FORCE: 50.0,
                MAX_THRUST: 1000.0,
                REVERSE_THRUST_FORCE: 5.0,
                DRAG_COEFFICIENT: 0.05,
                LIFT_COEFFICIENT: 0.0005,
                PITCH_SPEED: 0.05,
                ROLL_SPEED: 0.1,
                MAX_SPEED_LANDING: 60.0,
                MAX_SINK_RATE_LANDING: 12,
                TAKEOFF_SPEED: 50.0,
                AIRBORNE_CONFIRMATION_TIME: 5.0,
                GROUND_LEVEL: 0.5,
                RUNWAY_WIDTH: 40,
                RUNWAY_LENGTH: 700,
                SINK_RATE_THRESHOLD: 5,
            }
        },
        otter: {
            modelPath: 'model/TWIN_OTTER_NOAA_GND_0824.glb',
            scale: [150,150,150],
            rotation: [0, 0, 0],
            position: [0, -2.7, 0],
            propellorName: 'TWIN_OTTER_NOAA_GND_0824_3',
            followCameraOffset: [0, 10, -50],
            followSmoothCameraOffset: [30, 10, -30],
            cameraDistance: 35,
            cockpitCameraOffset: [0, -1, 13],
            hitBoxScaleX: 0.8,
            hitBoxScaleY: 0.5,
            hitBoxScaleZ: 0.8,
            constants: {
                GRAVITY: 20.0,
                THRUST_FORCE: 10.0,
                MAX_THRUST: 300.0,
                REVERSE_THRUST_FORCE: 10.0,
                DRAG_COEFFICIENT: 0.1,
                LIFT_COEFFICIENT: 0.01,
                PITCH_SPEED: 0.2,
                ROLL_SPEED: 0.3,
                MAX_SPEED_LANDING: 25.0,
                MAX_SINK_RATE_LANDING: 4,
                TAKEOFF_SPEED: 25.0,
                AIRBORNE_CONFIRMATION_TIME: 5.0,
                GROUND_LEVEL: 0.5,
                RUNWAY_WIDTH: 40,
                RUNWAY_LENGTH: 700,
                SINK_RATE_THRESHOLD: 5,
            }
        }
    };

    return models[modelName] || models['cessna']; // Default to cessna if model not found
}
